version: '2.35'

services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"

  gateway-service:
    build: ./gateway-service
    ports:
      - "8084:8080"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  site-service:
    build: ./site-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  organization-service:
    build: ./organization-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
