apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-service
  template:
    metadata:
      labels:
        app: site-service
    spec:
      containers:
        - name: site-service
          image: akash6637/site-service:latest
          ports:
            - containerPort: 8083
